services:
  - type: web
    name: emphub-backend
    runtime: docker
    plan: free   # ou starter, dependendo do seu plano
    envVars:
      - key: SUPABASE_URL
        value: https://pbcplcxasovlliscdthv.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiY3BsY3hhc292bGxpc2NkdGh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxODA2NTYsImV4cCI6MjA3Mjc1NjY1Nn0.jK8i73zS06p9Ymt7vslBQkhNDE__txfaj6JNjC_UTug
      - key: JWT_SECRET_KEY
        value: ia4u/UwSPS5bC2l4hyrqrd7B2a9+U1Vs42HAqGHCJMHdzme+9yWr7pBsaMQOTbqvESCZnkAOzvupf8Oa7I9YnA==
